definitions:
  services:
    docker:
      memory: 2048
    postgres:
      image: enroute/chouette-core-postgres
      environment:
        POSTGRES_DB: chouette
        POSTGRES_USER: chouette
        POSTGRES_PASSWORD: chouette
      memory: 2048
  caches:
    bundler: ./vendor/bundle
    yarn: ./node_modules
    assets: ./public/assets
    assets-cache: ./tmp/assets/cache
    build-cache: ./cache
  steps:
    - step: &unit-tests
        name: Unit tests
        image: ruby:2.6.4-slim-stretch
        size: 2x
        caches:
          - bundler
          - yarn
          - assets
          - assets-cache
          - build-cache
        script:
          - export LANG=en_US.UTF-8 LANGUAGE=en_US:UTF-8 LC_ALL=en_US.UTF-8
          - export BUNDLER_VERSION=2.0.2
          - export RAILS_DB_USER=chouette
          - export RAILS_DB_PASSWORD=chouette
          - export RAILS_DB_NAME=chouette
          - export RAILS_DB_HOST=localhost
          - export PARALLEL_TESTS=true

          - ./script/bitbucket-unit-tests-setup.sh

          - bundle exec rake ci
        services:
          - postgres

pipelines:
  custom:
    gems-update: # Merge ci-master from chouette-core
      - step:
          name: Update gems
          image: ruby:2.6.4-slim-stretch
          caches:
            - bundler
            - yarn
            - assets
            - assets-cache
            - build-cache
          script:
            - export LANG=en_US.UTF-8 LANGUAGE=en_US:UTF-8 LC_ALL=en_US.UTF-8
            - export BUNDLER_VERSION=2.0.2
            - export RAILS_DB_USER=chouette
            - export RAILS_DB_PASSWORD=chouette
            - export RAILS_DB_NAME=chouette
            - export RAILS_DB_HOST=localhost
            - export FAIL_FAST=true

            - ./script/bitbucket-unit-tests-setup.sh
            - ./script/bitbucket-bummr-pull-request.sh
          services:
            - postgres

  default:
    - step: *unit-tests

  branches:
    master:
      - step: *unit-tests
      - step:
          name: Build Docker
          image: google/cloud-sdk:latest
          caches:
            - docker
          script:
            - ./script/bitbucket-gcloud-configure-docker.sh
            - ./script/bitbucket-build-docker.sh
          services:
            - docker
      - step:
          name: Tag
          script:
            - export TAG_NAME=ci-master
            - git tag -afm "Build ${BITBUCKET_BUILD_NUMBER}" $TAG_NAME
            - git push origin :refs/tags/$TAG_NAME
            - git push origin $TAG_NAME
      - step:
          name: Trigger sub-projects
          script:
            - pipe: atlassian/trigger-pipeline:4.1.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                REPOSITORY: $TRIGGER_REPOSITORY_1
                CUSTOM_PIPELINE_NAME: 'merge'
            - pipe: atlassian/trigger-pipeline:4.1.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                REPOSITORY: $TRIGGER_REPOSITORY_2
                CUSTOM_PIPELINE_NAME: 'merge'
      - step:
          name: Deploy to test
          image: google/cloud-sdk:latest
          caches:
            - docker
          deployment: test
          script:
            - ./script/bitbucket-gcloud-configure-docker.sh
            # Tag image in registry with latest label
            - ./script/bitbucket-tag-docker.sh latest
            # Update test instance
            - ./script/bitbucket-update-image.sh
            - pipe: atlassian/datadog-send-event:1.0.1
              variables:
                API_KEY: $DATADOG_KEY
                TITLE: "Build ${BITBUCKET_BUILD_NUMBER} deployed on chouette-core test"
          services:
            - docker
