test: &default
  adapter: <%= SmartEnv['RAILS_DB_ADAPTER'] %>
  encoding: unicode
  pool: <%= SmartEnv['RAILS_DB_POOLSIZE'] %>
  host: <%= SmartEnv.fetch 'RAILS_DB_HOST', default: 'localhost' %>
  port: <%= SmartEnv['RAILS_DB_PORT'] %>
  schema_search_path: 'public,shared_extensions'
  postgis_schema: 'shared_extensions'
  database: <%= SmartEnv.fetch 'RAILS_DB_NAME', default: 'stif_boiv_test' %><%= SmartEnv['TEST_ENV_NUMBER'] %>
  username: <%= ENV['RAILS_DB_USER'] || ENV['POSTGRESQL_ENV_POSTGRES_USER'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] || ENV['POSTGRESQL_ENV_POSTGRES_PASSWORD'] %>

# Only used to build assets
production:
  <<: *default
